name: Auto Commit

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  push:
    branches:
      - main # Or your branch name
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make a change (replace with your logic)
        run: |
          echo "Automated update at $(date)" >> auto_generated_file.txt
      - name: List files and content
        run: |
          ls -al
          cat auto_generated_file.txt
      - name: Configure Git
        run: |
          git config --global user.email "i.shawn.yoon@gmail.com"
          git config --global user.name "Shawn Yoon"
      - name: Add and Commit
        run: |
          git add auto_generated_file.txt
          git commit --allow-empty -m "update job complete"
      - name: Push changes using alternative action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update"
          file_pattern: "auto_generated_file.txt"
