name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (most reliable on free tier)
  workflow_dispatch:       # Allow manual trigger too

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: Make a change (simulate auto update)
        run: |
          echo "Automated update at $(date)" >> auto_generated_file.txt

      - name: Configure Git
        run: |
          git config --global user.email "i.shawn.yoon@gmail.com"
          git config --global user.name "Shawn Yoon"

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update"
          file_pattern: "auto_generated_file.txt"
